import '@/styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Meta verificación de Google */}
        <meta name="google-site-verification" content="Dw6ZEE8PeEe1HjbzyOw2e2925WxzlWlGvbLpqnopqHM" />   
      </head>
      <body>{children}</body>
    </html>
  )
}
